# Generated by Django 4.2 on 2024-08-26 16:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="logo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[512, 512],
                upload_to="coins/",
                verbose_name="Logo",
            ),
        ),
    ]
