# Generated by Django 4.2 on 2024-08-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_coin_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="logo_url",
            field=models.URLField(blank=True, null=True, verbose_name="Logo URL"),
        ),
    ]
