# Generated by Django 4.2 on 2024-08-26 17:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_coin_logo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="logo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=90,
                scale=None,
                size=[1920, 1080],
                upload_to="coins/",
                verbose_name="Logo",
            ),
        ),
    ]
