# Generated by Django 4.2 on 2024-08-27 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0005_remove_coin_logo_url_alter_coin_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coin",
            options={"verbose_name": "Coin", "verbose_name_plural": "Coins"},
        ),
    ]
