# Generated by Django 4.2 on 2024-08-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0006_alter_coin_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
