# Generated by Django 4.2 on 2025-01-14 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0007_alloweduser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_user_id", models.PositiveIntegerField(unique=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EarningsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "shariah_status",
                    models.CharField(
                        choices=[
                            ("COMPLIANT", "Halal"),
                            ("NON_COMPLIANT", "Not Halal"),
                            ("QUESTIONABLE", "Doubtful"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=50,
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("time-pre-market", "Pre Market"),
                            ("time-not-supplied", "Not Supplied"),
                            ("time-after-hours", "After Hours"),
                        ],
                        default="time-not-supplied",
                        max_length=50,
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bot.symbol"
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "symbol")},
            },
        ),
    ]
