# Generated by Django 4.2 on 2025-01-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0008_symbol_telegramuser_earningsdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TelegramUser",
        ),
        migrations.AlterModelOptions(
            name="alloweduser",
            options={
                "verbose_name": "Allowed User",
                "verbose_name_plural": "Allowed Users",
            },
        ),
        migrations.AlterModelOptions(
            name="symbol",
            options={"verbose_name": "Symbol", "verbose_name_plural": "Symbols"},
        ),
        migrations.RemoveField(
            model_name="earningsdata",
            name="shariah_status",
        ),
        migrations.AddField(
            model_name="symbol",
            name="shariah_status",
            field=models.CharField(
                choices=[
                    ("COMPLIANT", "Halal"),
                    ("NON_COMPLIANT", "Not Halal"),
                    ("QUESTIONABLE", "Doubtful"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
