# Generated by Django 4.2 on 2025-01-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0009_delete_telegramuser_alter_alloweduser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symbol",
            name="shariah_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
