# Generated by Django 4.2 on 2025-01-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0010_alter_symbol_shariah_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symbol",
            name="shariah_status",
            field=models.CharField(
                choices=[
                    ("COMPLIANT", "COMPLIANT"),
                    ("NON_COMPLIANT", "NON_COMPLIANT"),
                    ("QUESTIONABLE", "QUESTIONABLE"),
                    ("UNKNOWN", "UNKNOWN"),
                ],
                default="UNKNOWN",
                max_length=50,
            ),
        ),
    ]
